In [1]:
import os
import re
import sys
import logging
import json
import numpy as np
import pandas as pd
import pickle
import xgboost as xgb
import plotly.graph_objects as go
from collections import defaultdict
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix

from typing import Optional
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import sys
import joblib
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sqlalchemy import create_engine
sys.path.append("/dss/work/rirg2545/actionable-hypotension/")



# ----------------------
# Configuration
# ----------------------
MODELS_DIR = "/dss/work/rirg2545/actionable-hypotension/models_given/calibrated"
SUBANALYSIS_DIR = "/dss/work/rirg2545/actionable-hypotension/extended_evaluation_review/results"
LOG_LEVEL = logging.INFO
# ----------------------
# Set up logging
# ----------------------
logging.basicConfig(
level=LOG_LEVEL,
format="%(asctime)s [%(levelname)s] %(message)s",
datefmt="%Y-%m-%d %H:%M:%S")
# -----
# DB connection
DATABASE_URI = "postgresql+psycopg2://rirg2545@localhost:5434/mimic"
engine = create_engine(DATABASE_URI, future=True)

decision_thresholds = {
"mix": 0.0011452179169282317,
"inv_model": 0.0020985996816307306,
"noninv_model": 0.0008126477478072047}

UNCALIBRATED_MODELS_DIR = "/dss/work/rirg2545/actionable-hypotension/models_given/uncalibrated"
CALIBRATED_MODELS_DIR = "/dss/work/rirg2545/actionable-hypotension/extended_evaluation_review/models_calibrated_unbundled"

CREATE TEST FULLS

In [2]:
def load_calibrated_model_predictions(
    model_name: str,
    x_val: pd.DataFrame,
    x_test: pd.DataFrame
):
    """
    Loads XGBoost model (JSON) + calibrator (pkl) and returns calibrated predictions.

    Returns:
        Tuple[np.ndarray, np.ndarray, Tuple[Booster, Calibrator]]:
            - y_val_pred (calibrated probabilities)
            - y_test_pred (calibrated probabilities)
            - (booster, calibrator)
    """
    import xgboost as xgb

    # --- Load model ---
    model_path = os.path.join(UNCALIBRATED_MODELS_DIR, f"{model_name}.json")
    logging.info(f"Lade Modell von: {model_path}")

    booster = xgb.Booster()
    booster.load_model(model_path)

    # --- Load calibrator ---
    calibrator_path = os.path.join(
        CALIBRATED_MODELS_DIR, f"{model_name}_calibrator.pkl"
    )
    logging.info(f"Lade Kalibrator von: {calibrator_path}")

    calibrator = joblib.load(calibrator_path)

    # --- Predict raw ---
    dval = xgb.DMatrix(x_val)
    dtest = xgb.DMatrix(x_test)

    y_val_raw = booster.predict(dval)
    y_test_raw = booster.predict(dtest)

    # --- Apply calibration ---
    y_val_pred = calibrator.transform(y_val_raw)
    y_test_pred = calibrator.transform(y_test_raw)

    return y_val_pred, y_test_pred, (booster, calibrator)

In [3]:
def load_and_prepare_data_xgb(table_name):
    
    cache = {} 
    if table_name in cache:
        logging.info(f"🔁 Using cached data for {table_name} ")
        return cache[table_name]

    logging.info(f" Loading val/test data from evaluation.{table_name}")
    

    df = pd.read_sql(f"""
        SELECT * FROM evaluation.{table_name}
        WHERE split IN ('val', 'test')
        ORDER BY subject_id, icustay_id, context_start
    """, engine)

    # Vorverarbeitung
    # IDs und Kontext separat sichern
    id_cols = ["subject_id", "icustay_id", "context_start", "context_end", "currently_on_cat", "cat_label"]
    id_df = df[id_cols + ["split"]].copy()

    # Label engineering
    df["label"] = df["positive_event"].astype(int)

    excluded = {"positive_event", "positive_sample", "split", "label", "treatment_given", "only_2_values"} | set(id_cols)
    
    logging.info(f"Features excluded: {excluded}")

    feature_cols = [c for c in df.columns if c not in excluded]

    val_df = df[df["split"] == "val"]
    test_df = df[df["split"] == "test"]

    x_val = val_df[feature_cols]
    y_val = val_df["label"]
    x_test = test_df[feature_cols]
    y_test = test_df["label"]

    # Reihenfolge:
    # Die IDs passend zum Split filtern
    id_val = id_df[id_df["split"] == "val"].reset_index(drop=True)
    id_test = id_df[id_df["split"] == "test"].reset_index(drop=True)

    logging.info(f"✅ Data loaded and cached for {table_name}")

    cache[table_name] = (x_val, y_val, x_test, y_test, feature_cols, id_val, id_test)
    return cache[table_name]

In [4]:
def create_test_full_for_table(table_name: str):
    """
    Erstellt ein DataFrame `test_full` mit Features, Label und Modellvorhersage.
    Zusätzliche features für Subgruppenanalyse: 
    """

    # Modellname und Tabellennamen anpassen
    model_name = f"xgb_{table_name}"
    table_name = f"merged_{table_name}_features_w_cat_status_w_label" # updated to include the subgroup-info "currently on cat yes or no"

    # Lade Daten einmal – inkl. y-Test und den indices für val und test
    x_val, y_val, x_test, y_test, feature_cols, id_val, id_test = load_and_prepare_data_xgb(table_name)

    # Lade Modell und Vorhersagen machen

    y_val_pred, y_test_pred, model = load_calibrated_model_predictions(model_name, x_val, x_test)

    # Erstelle Test-Full-DataFrame
    test_full = x_test.copy()
    test_full["label"] = y_test.values
    test_full["preds"] = y_test_pred

    # Jetzt: concat id_test (Identifikatoren und context_start) mit test_full (Features, Label, Preds)
    test_full = pd.concat([id_test.reset_index(drop=True), test_full.reset_index(drop=True)], axis=1)

    #### Mehrere Zusatzinformationen für die Subgruppenanalyse aus der originalen tabelle holen + neue erstellen ####

    # >>>>> Extended_Evaluation_Columns <<<<<
    # updated to include each individual exclusion criteria
    extended_evaluation_df = pd.read_sql(f"""
    SELECT f.icustay_id, f.subject_id, f.transplant, f.stroke,f.brain_injury,f.brain_hemorrhage, f.exclusion, f.age, f.saps_score, f.sapsii_score, f.sofa_score, f.icu_type, f.heart_surgery_patient
    FROM evaluation.fused_subgroups_mv_excluded_unpacked f
    JOIN ce_approach.split_all_subjects s ON f.subject_id = s.subject_id
    WHERE s.split = 'test'
""", engine)
    
    
    # Merge der Zusatzinfos: exclusion,age etc.)
    test_full = test_full.merge(extended_evaluation_df, on=["icustay_id", "subject_id"], how="left")
    

    return test_full

In [5]:
def create_all_test_fulls(table_names: list[str]) -> dict[str, pd.DataFrame]:
    """
    Erstellt test_full DataFrames für alle angegebenen Tabellen.
    
    Returns:
        dict mapping model name (e.g. 'mix_model') to its test_full DataFrame
    """
    dfs = {}
    for table_name in table_names:
        dfs[table_name] = create_test_full_for_table(table_name)
    return dfs

In [6]:
def bootstrap_auc(y_true, y_pred, n_bootstrap=1000, ci=0.95, seed=42):
    """
    Returns (auc, lower, upper) using percentile bootstrap.
    """
    rng = np.random.default_rng(seed)
    aucs = []
    n = len(y_true)
    y_true_arr = np.array(y_true)
    y_pred_arr = np.array(y_pred)

    for _ in range(n_bootstrap):
        idx = rng.integers(0, n, size=n)
        y_t = y_true_arr[idx]
        y_p = y_pred_arr[idx]
        if len(np.unique(y_t)) < 2:
            continue  # skip degenerate bootstrap samples
        aucs.append(roc_auc_score(y_t, y_p))

    alpha = (1 - ci) / 2
    lower = np.percentile(aucs, 100 * alpha)
    upper = np.percentile(aucs, 100 * (1 - alpha))
    point = roc_auc_score(y_true_arr, y_pred_arr)
    return point, lower, upper

## Evaluate Subgroups

In [14]:
def build_subgroup_configs(df: pd.DataFrame) -> list[dict]:
    """
    Define all subgroups as filter configurations.
    Each entry: name, filter_condition, and optional metadata.
    """
    configs = [
        
        # --- last MAP ---
        {"name": "last < 65",
         "filter": lambda df: df["last"] <= 65},
        {"name": "last 70-80",
         "filter": lambda df: (df["last"] > 65) & (df["last"] <= 70)},
        {"name": "last 80-85",
         "filter": lambda df: (df["last"] > 70) & (df["last"] <= 100)},
        {"name": "last > 85",
         "filter": lambda df: df["last"] > 100},
         
        
    ]
    return configs

In [8]:
def build_subgroup_configs(df: pd.DataFrame) -> list[dict]:
    """
    Define all subgroups as filter configurations.
    Each entry: name, filter_condition, and optional metadata.
    """
    configs = [
        
        # --- Baseline ---
        {"name": "All patients",
         "filter": None},
         # --- Catecholamine subgroup analyses ---
        {"name": "No catecholamine event",
        "filter": lambda df: df["cat_label"] == "negative"},

        {"name": "All vasopressors (any catecholamine)",
        "filter": lambda df: df["cat_label"] != "negative"},

        {"name": "Norepinephrine events",
        "filter": lambda df: df["cat_label"].isin(["Norepinephrine", "negative"])},

        {"name": "Vasopressin events",
        "filter": lambda df: df["cat_label"].isin(["Vasopressin", "negative"])},

        {"name": "Epinephrine events",
        "filter": lambda df: df["cat_label"].isin(["Epinephrine", "negative"])},

        {"name": "Dopamine events",
        "filter": lambda df: df["cat_label"].isin(["Dopamine", "negative"])},

        {"name": "Dobutamine events",
        "filter": lambda df: df["cat_label"].isin(["Dobutamine", "negative"])},

        {"name": "Phenylephrine events",
        "filter": lambda df: df["cat_label"].isin(["Phenylephrine", "negative"])},

        {"name": "Milrinone events",
        "filter": lambda df: df["cat_label"].isin(["Milrinone", "negative"])},

        {"name": "Vasopressor-dominant agents",
        "filter": lambda df: df["cat_label"].isin(["Norepinephrine", "Phenylephrine", "Vasopressin", "negative"])},

        {"name": "Inotrope-dominant agents",
        "filter": lambda df: df["cat_label"].isin(["Dobutamine", "Milrinone","negative"])},

        {"name": "Mixes-action agents",
        "filter": lambda df: df["cat_label"].isin(["Dopamine", "Epinephrine", "negative"])},
        # --- Exclusion ---
        {"name": "Excluded patients_all",
         "filter": lambda df: df["exclusion"] == 1},
        {"name": "Non-excluded patients",
         "filter": lambda df: df["exclusion"] == 0},
          # --- Clinical subgroups ---
        {"name": "Transplant patients",
         "filter": lambda df: df["transplant"] == 1},
        {"name": "Non-transplant patients",
         "filter": lambda df: df["transplant"] == 0},
        {"name": "Stroke patients",
         "filter": lambda df: df["stroke"] == 1},
        {"name": "Non-stroke patients",
         "filter": lambda df: df["stroke"] == 0},
        {"name": "Brain injury patients",
         "filter": lambda df: df["brain_injury"] == 1},
        {"name": "Non-brain injury patients",
         "filter": lambda df: df["brain_injury"] == 0},
        {"name": "Brain hemorrhage patients",
         "filter": lambda df: df["brain_hemorrhage"] == 1},
        {"name": "Non-brain hemorrhage patients",
         "filter": lambda df: df["brain_hemorrhage"] == 0},

         # --- currently on catecholamines ---
        {"name": "On Catecholamines",
         "filter": lambda df: df["currently_on_cat"] == 1},
        {"name": "Not on catecholamines",
         "filter": lambda df: df["currently_on_cat"] == 0},

        # --- Age ---
        {"name": "Age < 70",
         "filter": lambda df: df["age"] < 70},
        {"name": "Age 70-80",
         "filter": lambda df: (df["age"] >= 70) & (df["age"] < 80)},
        {"name": "Age 80-85",
         "filter": lambda df: (df["age"] >= 80) & (df["age"] < 85)},
        {"name": "Age > 85",
         "filter": lambda df: df["age"] > 85},

        # --- ICU type ---
        {"name": "Surgical ICU",
         "filter": lambda df: df["icu_type"] == "surgical"},
        {"name": "Non-surgical ICU",
         "filter": lambda df: df["icu_type"] == "non-surgical"},

        # --- Heart surgery ---
        {"name": "Heart surgery",
         "filter": lambda df: df["heart_surgery_patient"] == 1},
        {"name": "No heart surgery",
         "filter": lambda df: df["heart_surgery_patient"] == 0},

           # --- SOFA clinical cutoffs ---
        {"name": "SOFA < 6 (low severity)",
         "filter": lambda df: df["sofa_score"] < 6},
        {"name": "SOFA 6-10 (moderate severity)",
         "filter": lambda df: (df["sofa_score"] >= 6) & (df["sofa_score"] <= 10)},
        {"name": "SOFA >= 11 (high severity)",
         "filter": lambda df: df["sofa_score"] >= 11},

        # --- SOFA tertiles (data-driven) ---
        {"name": "SOFA low (tertile 1)",
         "filter": lambda df: df["sofa_score"] <= df["sofa_score"].quantile(0.33)},
        {"name": "SOFA mid (tertile 2)",
         "filter": lambda df: (df["sofa_score"] > df["sofa_score"].quantile(0.33)) &
                              (df["sofa_score"] <= df["sofa_score"].quantile(0.66))},
        {"name": "SOFA high (tertile 3)",
         "filter": lambda df: df["sofa_score"] > df["sofa_score"].quantile(0.66)},

        # --- SAPS I clinical cutoffs (range 0-56) ---
        {"name": "SAPS I < 14 (low severity)",
         "filter": lambda df: df["saps_score"] < 14},
        {"name": "SAPS I 14-24 (moderate severity)",
         "filter": lambda df: (df["saps_score"] >= 14) & (df["saps_score"] <= 24)},
        {"name": "SAPS I >= 25 (high severity)",
         "filter": lambda df: df["saps_score"] >= 25},

        # --- SAPS I tertiles (data-driven) ---
        {"name": "SAPS I low (tertile 1)",
         "filter": lambda df: df["saps_score"] <= df["saps_score"].quantile(0.33)},
        {"name": "SAPS I mid (tertile 2)",
         "filter": lambda df: (df["saps_score"] > df["saps_score"].quantile(0.33)) &
                              (df["saps_score"] <= df["saps_score"].quantile(0.66))},
        {"name": "SAPS I high (tertile 3)",
         "filter": lambda df: df["saps_score"] > df["saps_score"].quantile(0.66)},

        # --- SAPS II clinical cutoffs (range 0-163)---
        {"name": "SAPS II < 40 (low severity)",
         "filter": lambda df: df["sapsii_score"] < 40},
        {"name": "SAPS II 40-51 (moderate severity)",
         "filter": lambda df: (df["sapsii_score"] >= 40) & (df["sapsii_score"] <= 51)},
        {"name": "SAPS II >= 52 (high severity)",
         "filter": lambda df: df["sapsii_score"] >= 52},

        # --- SAPS II tertiles (data-driven) ---
        {"name": "SAPS II low (tertile 1)",
         "filter": lambda df: df["sapsii_score"] <= df["sapsii_score"].quantile(0.33)},
        {"name": "SAPS II mid (tertile 2)",
         "filter": lambda df: (df["sapsii_score"] > df["sapsii_score"].quantile(0.33)) &
                              (df["sapsii_score"] <= df["sapsii_score"].quantile(0.66))},
        {"name": "SAPS II high (tertile 3)",
         "filter": lambda df: df["sapsii_score"] > df["sapsii_score"].quantile(0.66)}

        
    ]
    return configs

In [9]:
def evaluate_subgroup(
    df: pd.DataFrame,
    filter_condition=None,
    label_col: str = "label",
    pred_col: str = "preds",
    threshold_value: int = 0,
    model_name: str = "Unnamed Model",
    name: str = "Unnamed Subgroup",
    n_bootstrap: int = 1000,
    ci: float = 0.95,
    min_samples: int = 30,
    verbose: bool = True
) -> dict | None:
    """
    Evaluates a subgroup of the test set.
    Returns AUC with bootstrapped CI, sensitivity, specificity.
    """

    # --- Apply filter ---
    if filter_condition is None:
        subset = df
    elif callable(filter_condition):
        subset = df[filter_condition(df)]
    else:
        subset = df[filter_condition]

    if len(subset) < min_samples:
        if verbose:
            print(f"Skipping '{name}' (n={len(subset)}) - too small.")
        return None

    y_true = subset[label_col]
    y_pred = subset[pred_col]

    if len(np.unique(y_true)) < 2:
        if verbose:
            print(f"Skipping '{name}' - only one class present.")
        return None

    # --- Bootstrapped AUC ---
    auc, lower, upper = bootstrap_auc(
        y_true, y_pred, n_bootstrap=n_bootstrap, ci=ci
    )

    # --- Get threshold for this model ---
    if threshold_value is None:
        raise ValueError("threshold must be provided.")

    # --- Sensitivity / Specificity ---
    y_pred_label = (y_pred >= threshold_value).astype(int)
    cm = confusion_matrix(y_true, y_pred_label)
    tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0, 0, 0, 0)

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else float("nan")
    specificity = tn / (tn + fp) if (tn + fp) > 0 else float("nan")

    n_pos = int(y_true.sum())
    n_total = len(y_true)

    if verbose:
        print(f"[{model_name}] {name}")
        print(f"  → N = {n_total} | N_pos = {n_pos}")
        print(f"  → AUC = {auc:.3f} [{lower:.3f}–{upper:.3f}]")
        print(f"  → Threshold = {threshold_value:.6f}")
        print(f"  → Sensitivity = {sensitivity:.3f} | Specificity = {specificity:.3f}")

    return {
        "auc": auc,
        "auc_lower": lower,
        "auc_upper": upper,
        "n_pos": n_pos,
        "n_total": n_total,
        "sensitivity": sensitivity,
        "specificity": specificity,
        "threshold": threshold_value
    }

In [10]:
def evaluate_all_subgroups_latex_ready(
    
    threshold_dict: dict,
    min_samples: int = 30,
    n_bootstrap: int = 1000,
    ci: float = 0.95,
    verbose: bool = True
) -> pd.DataFrame:
    """
    Config-driven subgroup evaluation across all models.
    Calls evaluate_subgroup per config entry.
    Output: one row per subgroup, one column per model.
    Cell format: AUC [lower–upper], n_pos/n_total, sens, spec
    """
    dfs = create_all_test_fulls(["mix"])
    subgroup_rows = defaultdict(dict)

    for model_name, df in dfs.items():
        threshold = threshold_dict.get(model_name)
        if threshold is None:
            raise ValueError(f"Threshold für Modell '{model_name}' nicht gefunden.")

        configs = build_subgroup_configs(df)

        for cfg in configs:
            name = cfg["name"]
            result = evaluate_subgroup(
                df=df,
                filter_condition=cfg["filter"],
                label_col="label",
                pred_col="preds",
                threshold_value=threshold,
                model_name=model_name,
                name=name,
                n_bootstrap=n_bootstrap,
                ci=ci,
                min_samples=min_samples,
                verbose=verbose
            )

            if result is None:
                continue

            subgroup_rows[name][model_name] = (
                f"{result['auc']:.3f} [{result['auc_lower']:.3f}–{result['auc_upper']:.3f}], "
                f"{result['n_pos']}/{result['n_total']}, "
                f"{result['sensitivity']:.3f}, "
                f"{result['specificity']:.3f}"
            )

    # Assemble latex-ready DataFrame
    rows = []
    for name, model_entries in subgroup_rows.items():
        row = {"Subgroup": name}
        for model_name in dfs.keys():
            row[model_name] = model_entries.get(model_name, "—")
        rows.append(row)

    return pd.DataFrame(rows).set_index("Subgroup")

Aufruf

In [11]:

results = evaluate_all_subgroups_latex_ready(
    threshold_dict=decision_thresholds,
    min_samples = 30,
    n_bootstrap = 1000,
    ci = 0.95,
    verbose = True) 

    
#print(type(results))

#results.to_csv(os.path.join(SUBANALYSIS_DIR, "results_subgroup_analysis_newest_2.csv"), index=False)

2026-04-27 12:54:15 [INFO]  Loading val/test data from evaluation.merged_mix_features_w_cat_status_w_label
2026-04-27 12:54:43 [INFO] Features excluded: {'currently_on_cat', 'icustay_id', 'subject_id', 'only_2_values', 'treatment_given', 'label', 'context_start', 'cat_label', 'context_end', 'positive_sample', 'positive_event', 'split'}
2026-04-27 12:54:43 [INFO] ✅ Data loaded and cached for merged_mix_features_w_cat_status_w_label
2026-04-27 12:54:43 [INFO] Lade Modell von: /dss/work/rirg2545/actionable-hypotension/models_given/uncalibrated/xgb_mix.json
2026-04-27 12:54:44 [INFO] Lade Kalibrator von: /dss/work/rirg2545/actionable-hypotension/extended_evaluation_review/models_calibrated_unbundled/xgb_mix_calibrator.pkl

[mix] All patients
  → N = 1116174 | N_pos = 2256
  → AUC = 0.823 [0.814–0.831]
  → Threshold = 0.001145
  → Sensitivity = 0.853 | Specificity = 0.612
Skipping 'No catecholamine event' - only one class present.
Skipping 'All vasopressors (any catecholamine)' - only one class present.
[mix] Norepinephrine events
  → N = 1114640 | N_pos = 722
  → AUC = 0.835 [0.821–0.849]
  → Threshold = 0.001145
  → Sensitivity = 0.871 | Specificity = 0.612
[mix] Vasopressin events
  → N = 1114106 | N_pos = 188
  → AUC = 0.859 [0.833–0.882]
  → Threshold = 0.001145
  → Sensitivity = 0.915 | Specificity = 0.612
[mix] Epinephrine events
  → N = 1113980 | N_pos = 62
  → AUC = 0.913 [0.881–0.942]
  → Threshold = 0.001145
  → Sensitivity = 0.968 | Specificity = 0.612
[mix] Dopamine events
  → N = 1114020 | N_pos = 102
  → AUC = 0.850 [0.814–0.882]
  → Threshold = 0.001145
  → Sensitivity = 0.882 | Specificity = 0.612
[mix] Dobutamine events
  → N = 1113950 | N_pos = 32
  → AUC = 0.871 [0.806–0.919]
  → Threshold = 0.001145
  → Sensitivity = 0.906 | Specificity = 0.612
[mix] Phenylephrine events
  → N = 1115012 | N_pos = 1094
  → AUC = 0.801 [0.789–0.813]
  → Threshold = 0.001145
  → Sensitivity = 0.821 | Specificity = 0.612
[mix] Milrinone events
  → N = 1113974 | N_pos = 56
  → AUC = 0.792 [0.742–0.841]
  → Threshold = 0.001145
  → Sensitivity = 0.839 | Specificity = 0.612
[mix] Vasopressor-dominant agents
  → N = 1115922 | N_pos = 2004
  → AUC = 0.819 [0.809–0.827]
  → Threshold = 0.001145
  → Sensitivity = 0.848 | Specificity = 0.612
[mix] Inotrope-dominant agents
  → N = 1114006 | N_pos = 88
  → AUC = 0.820 [0.780–0.859]
  → Threshold = 0.001145
  → Sensitivity = 0.864 | Specificity = 0.612
[mix] Mixes-action agents
  → N = 1114082 | N_pos = 164
  → AUC = 0.874 [0.848–0.899]
  → Threshold = 0.001145
  → Sensitivity = 0.915 | Specificity = 0.612
[mix] Excluded patients_all
  → N = 201541 | N_pos = 350
  → AUC = 0.761 [0.733–0.788]
  → Threshold = 0.001145
  → Sensitivity = 0.669 | Specificity = 0.722
[mix] Non-excluded patients
  → N = 914357 | N_pos = 1904
  → AUC = 0.834 [0.826–0.842]
  → Threshold = 0.001145
  → Sensitivity = 0.887 | Specificity = 0.588
[mix] Transplant patients
  → N = 30205 | N_pos = 59
  → AUC = 0.833 [0.779–0.882]
  → Threshold = 0.001145
  → Sensitivity = 0.831 | Specificity = 0.687
[mix] Non-transplant patients
  → N = 1085693 | N_pos = 2195
  → AUC = 0.822 [0.813–0.831]
  → Threshold = 0.001145
  → Sensitivity = 0.854 | Specificity = 0.610
[mix] Stroke patients
  → N = 59149 | N_pos = 106
  → AUC = 0.731 [0.672–0.790]
  → Threshold = 0.001145
  → Sensitivity = 0.660 | Specificity = 0.701
[mix] Non-stroke patients
  → N = 1056749 | N_pos = 2148
  → AUC = 0.827 [0.818–0.835]
  → Threshold = 0.001145
  → Sensitivity = 0.863 | Specificity = 0.607
[mix] Brain injury patients
  → N = 51459 | N_pos = 49
  → AUC = 0.843 [0.781–0.893]
  → Threshold = 0.001145
  → Sensitivity = 0.776 | Specificity = 0.716
[mix] Non-brain injury patients
  → N = 1064439 | N_pos = 2205
  → AUC = 0.821 [0.813–0.830]
  → Threshold = 0.001145
  → Sensitivity = 0.855 | Specificity = 0.607
[mix] Brain hemorrhage patients
  → N = 112822 | N_pos = 206
  → AUC = 0.748 [0.715–0.781]
  → Threshold = 0.001145
  → Sensitivity = 0.597 | Specificity = 0.748
[mix] Non-brain hemorrhage patients
  → N = 1003076 | N_pos = 2048
  → AUC = 0.832 [0.823–0.840]
  → Threshold = 0.001145
  → Sensitivity = 0.879 | Specificity = 0.597
[mix] On Catecholamines
  → N = 188213 | N_pos = 809
  → AUC = 0.692 [0.672–0.711]
  → Threshold = 0.001145
  → Sensitivity = 0.894 | Specificity = 0.250
[mix] Not on catecholamines
  → N = 927961 | N_pos = 1447
  → AUC = 0.844 [0.834–0.854]
  → Threshold = 0.001145
  → Sensitivity = 0.831 | Specificity = 0.685
[mix] Age < 70
  → N = 645553 | N_pos = 1149
  → AUC = 0.825 [0.812–0.837]
  → Threshold = 0.001145
  → Sensitivity = 0.842 | Specificity = 0.646
[mix] Age 70-80
  → N = 232597 | N_pos = 618
  → AUC = 0.809 [0.794–0.823]
  → Threshold = 0.001145
  → Sensitivity = 0.861 | Specificity = 0.560
[mix] Age 80-85
  → N = 114824 | N_pos = 238
  → AUC = 0.826 [0.797–0.852]
  → Threshold = 0.001145
  → Sensitivity = 0.861 | Specificity = 0.570
[mix] Age > 85
  → N = 101109 | N_pos = 200
  → AUC = 0.826 [0.798–0.853]
  → Threshold = 0.001145
  → Sensitivity = 0.880 | Specificity = 0.572
[mix] Surgical ICU
  → N = 555050 | N_pos = 1287
  → AUC = 0.811 [0.799–0.822]
  → Threshold = 0.001145
  → Sensitivity = 0.833 | Specificity = 0.613
[mix] Non-surgical ICU
  → N = 560848 | N_pos = 967
  → AUC = 0.838 [0.827–0.850]
  → Threshold = 0.001145
  → Sensitivity = 0.880 | Specificity = 0.611
[mix] Heart surgery
  → N = 254065 | N_pos = 799
  → AUC = 0.798 [0.783–0.813]
  → Threshold = 0.001145
  → Sensitivity = 0.892 | Specificity = 0.499
[mix] No heart surgery
  → N = 861833 | N_pos = 1455
  → AUC = 0.825 [0.815–0.836]
  → Threshold = 0.001145
  → Sensitivity = 0.832 | Specificity = 0.645
[mix] SOFA < 6 (low severity)
  → N = 636413 | N_pos = 824
  → AUC = 0.846 [0.833–0.859]
  → Threshold = 0.001145
  → Sensitivity = 0.837 | Specificity = 0.686
[mix] SOFA 6-10 (moderate severity)
  → N = 337523 | N_pos = 876
  → AUC = 0.793 [0.779–0.807]
  → Threshold = 0.001145
  → Sensitivity = 0.869 | Specificity = 0.532
[mix] SOFA >= 11 (high severity)
  → N = 141962 | N_pos = 554
  → AUC = 0.768 [0.747–0.787]
  → Threshold = 0.001145
  → Sensitivity = 0.852 | Specificity = 0.470
[mix] SOFA low (tertile 1)
  → N = 385666 | N_pos = 408
  → AUC = 0.849 [0.829–0.869]
  → Threshold = 0.001145
  → Sensitivity = 0.809 | Specificity = 0.727
[mix] SOFA mid (tertile 2)
  → N = 412333 | N_pos = 738
  → AUC = 0.827 [0.814–0.842]
  → Threshold = 0.001145
  → Sensitivity = 0.864 | Specificity = 0.602
[mix] SOFA high (tertile 3)
  → N = 317899 | N_pos = 1108
  → AUC = 0.771 [0.756–0.784]
  → Threshold = 0.001145
  → Sensitivity = 0.862 | Specificity = 0.486
[mix] SAPS I < 14 (low severity)
  → N = 118024 | N_pos = 69
  → AUC = 0.862 [0.812–0.905]
  → Threshold = 0.001145
  → Sensitivity = 0.754 | Specificity = 0.803
[mix] SAPS I 14-24 (moderate severity)
  → N = 795706 | N_pos = 1491
  → AUC = 0.817 [0.806–0.828]
  → Threshold = 0.001145
  → Sensitivity = 0.848 | Specificity = 0.616
[mix] SAPS I >= 25 (high severity)
  → N = 202168 | N_pos = 694
  → AUC = 0.791 [0.774–0.807]
  → Threshold = 0.001145
  → Sensitivity = 0.873 | Specificity = 0.486
[mix] SAPS I low (tertile 1)
  → N = 382504 | N_pos = 380
  → AUC = 0.841 [0.821–0.863]
  → Threshold = 0.001145
  → Sensitivity = 0.813 | Specificity = 0.723
[mix] SAPS I mid (tertile 2)
  → N = 392760 | N_pos = 814
  → AUC = 0.817 [0.804–0.831]
  → Threshold = 0.001145
  → Sensitivity = 0.865 | Specificity = 0.590
[mix] SAPS I high (tertile 3)
  → N = 340634 | N_pos = 1060
  → AUC = 0.788 [0.774–0.802]
  → Threshold = 0.001145
  → Sensitivity = 0.858 | Specificity = 0.512
[mix] SAPS II < 40 (low severity)
  → N = 583597 | N_pos = 803
  → AUC = 0.840 [0.826–0.852]
  → Threshold = 0.001145
  → Sensitivity = 0.827 | Specificity = 0.692
[mix] SAPS II 40-51 (moderate severity)
  → N = 262660 | N_pos = 507
  → AUC = 0.826 [0.807–0.843]
  → Threshold = 0.001145
  → Sensitivity = 0.882 | Specificity = 0.571
[mix] SAPS II >= 52 (high severity)
  → N = 269641 | N_pos = 944
  → AUC = 0.771 [0.757–0.787]
  → Threshold = 0.001145
  → Sensitivity = 0.860 | Specificity = 0.478
[mix] SAPS II low (tertile 1)
  → N = 387192 | N_pos = 413
  → AUC = 0.863 [0.845–0.881]
  → Threshold = 0.001145
  → Sensitivity = 0.835 | Specificity = 0.727
[mix] SAPS II mid (tertile 2)
  → N = 362759 | N_pos = 703
  → AUC = 0.810 [0.794–0.826]
  → Threshold = 0.001145
  → Sensitivity = 0.849 | Specificity = 0.607
[mix] SAPS II high (tertile 3)
  → N = 365947 | N_pos = 1138
  → AUC = 0.783 [0.771–0.797]
  → Threshold = 0.001145
  → Sensitivity = 0.862 | Specificity = 0.495

In [15]:
results = evaluate_all_subgroups_latex_ready(
    threshold_dict=decision_thresholds,
    min_samples = 30,
    n_bootstrap = 1000,
    ci = 0.95,
    verbose = True) 

results.to_csv(os.path.join(SUBANALYSIS_DIR, "extended_subgroup_analysis_v5.csv"), index=True)

# - Decomposition of endpoint
# unit context
# icu type
# heart surgery yes no 
# -age
# severity (sofa, saps 2)
# - special/excluded patients:
# transplant
# stroke
# brain injury 
# brain hemorhhage 
# exclusion_all

2026-04-27 14:00:02 [INFO]  Loading val/test data from evaluation.merged_mix_features_w_cat_status_w_label
2026-04-27 14:00:34 [INFO] Features excluded: {'currently_on_cat', 'icustay_id', 'subject_id', 'only_2_values', 'treatment_given', 'label', 'context_start', 'cat_label', 'context_end', 'positive_sample', 'positive_event', 'split'}
2026-04-27 14:00:35 [INFO] ✅ Data loaded and cached for merged_mix_features_w_cat_status_w_label
2026-04-27 14:00:35 [INFO] Lade Modell von: /dss/work/rirg2545/actionable-hypotension/models_given/uncalibrated/xgb_mix.json
2026-04-27 14:00:35 [INFO] Lade Kalibrator von: /dss/work/rirg2545/actionable-hypotension/extended_evaluation_review/models_calibrated_unbundled/xgb_mix_calibrator.pkl

[mix] last < 65
  → N = 228988 | N_pos = 1069
  → AUC = 0.778 [0.764–0.792]
  → Threshold = 0.001145
  → Sensitivity = 0.968 | Specificity = 0.207
[mix] last 70-80
  → N = 147174 | N_pos = 325
  → AUC = 0.754 [0.729–0.777]
  → Threshold = 0.001145
  → Sensitivity = 0.874 | Specificity = 0.462
[mix] last 80-85
  → N = 649329 | N_pos = 763
  → AUC = 0.808 [0.792–0.823]
  → Threshold = 0.001145
  → Sensitivity = 0.713 | Specificity = 0.758
[mix] last > 85
  → N = 90683 | N_pos = 99
  → AUC = 0.797 [0.747–0.844]
  → Threshold = 0.001145
  → Sensitivity = 0.626 | Specificity = 0.826

In [19]:
df = pd.read_csv(
    os.path.join(SUBANALYSIS_DIR, "extended_subgroup_analysis_v3.csv"),
    index_col=0
)

df

,AUROC [CI],pos/total,Sensitivity,Specificity
Subgroup,,,,
All patients,0.823 [0.814–0.831],2256/1116174,0.853,0.612
Norepinephrine events,0.835 [0.821–0.849],722/1114640,0.871,0.612
Vasopressin events,0.859 [0.833–0.882],188/1114106,0.915,0.612
Epinephrine events,0.913 [0.881–0.942],62/1113980,0.968,0.612
Dopamine events,0.850 [0.814–0.882],102/1114020,0.882,0.612
Dobutamine events,0.871 [0.806–0.919],32/1113950,0.906,0.612
Phenylephrine events,0.801 [0.789–0.813],1094/1115012,0.821,0.612
Milrinone events,0.792 [0.742–0.841],56/1113974,0.839,0.612
Vasopressor-dominant agents,0.819 [0.809–0.827],2004/1115922,0.848,0.612
Inotrope-dominant agents,0.820 [0.780–0.859],88/1114006,0.864,0.612
Excluded patients_all,0.761 [0.733–0.788],350/201541,0.669,0.722
Non-excluded patients_all,0.834 [0.826–0.842],1904/914357,0.887,0.588
On Catecholamines at prediction time,0.692 [0.672–0.711],809/188213,0.894,0.250
Not on catecholamines at prediction time,0.844 [0.834–0.854],1447/927961,0.831,0.685
Age < 70,0.825 [0.812–0.837],1149/645553,0.842,0.646
Age 70-80,0.809 [0.794–0.823],618/232597,0.861,0.560
Age 80-85,0.826 [0.797–0.852],238/114824,0.861,0.570
Age > 85,0.826 [0.798–0.853],200/101109,0.880,0.572
Surgical ICU,0.811 [0.799–0.822],1287/555050,0.833,0.613
Non-surgical ICU,0.838 [0.827–0.850],967/560848,0.880,0.611
Heart surgery,0.798 [0.783–0.813],799/254065,0.892,0.499
No heart surgery,0.825 [0.815–0.836],1455/861833,0.832,0.645
SOFA < 6 (low severity),0.846 [0.833–0.859],824/636413,0.837,0.686
SOFA 6-10 (moderate severity),0.793 [0.779–0.807],876/337523,0.869,0.532
SOFA >= 11 (high severity),0.768 [0.747–0.787],554/141962,0.852,0.470
SOFA low (tertile 1),0.849 [0.829–0.869],408/385666,0.809,0.727
SOFA mid (tertile 2),0.827 [0.814–0.842],738/412333,0.864,0.602
SOFA high (tertile 3),0.771 [0.756–0.784],1108/317899,0.862,0.486
SAPS I < 14 (low severity),0.862 [0.812–0.905],69/118024,0.754,0.803
SAPS I 14-24 (moderate severity),0.817 [0.806–0.828],1491/795706,0.848,0.616
SAPS I >= 25 (high severity),0.791 [0.774–0.807],694/202168,0.873,0.486
SAPS I low (tertile 1),0.841 [0.821–0.863],380/382504,0.813,0.723
SAPS I mid (tertile 2),0.817 [0.804–0.831],814/392760,0.865,0.590
SAPS I high (tertile 3),0.788 [0.774–0.802],1060/340634,0.858,0.512
SAPS II < 40 (low severity),0.840 [0.826–0.852],803/583597,0.827,0.692
SAPS II 40-51 (moderate severity),0.826 [0.807–0.843],507/262660,0.882,0.571
SAPS II >= 52 (high severity),0.771 [0.757–0.787],944/269641,0.860,0.478
SAPS II low (tertile 1),0.863 [0.845–0.881],413/387192,0.835,0.727
SAPS II mid (tertile 2),0.810 [0.794–0.826],703/362759,0.849,0.607
SAPS II high (tertile 3),0.783 [0.771–0.797],1138/365947,0.862,0.495

In [13]:
df = pd.read_csv(
    os.path.join(SUBANALYSIS_DIR, "extended_subgroup_analysis_v2.csv"),
    index_col=0
)

df

,AUROC [CI],pos/total,Sensitivity,Specificity
Subgroup,,,,
All patients,0.822 [0.813–0.830],2212/1116130,0.852,0.612
Excluded patients,0.758 [0.731–0.784],343/201534,0.665,0.722
Non-excluded patients,0.834 [0.826–0.842],1867/914320,0.886,0.588
Age < 70,0.824 [0.812–0.835],1133/645537,0.839,0.646
Age 70-80,0.809 [0.791–0.824],602/232581,0.864,0.560
Age 80-85,0.823 [0.794–0.850],231/114817,0.857,0.570
Age > 85,0.827 [0.798–0.856],196/101105,0.878,0.572
Surgical ICU,0.810 [0.798–0.822],1268/555031,0.833,0.613
Non-surgical ICU,0.836 [0.825–0.848],942/560823,0.878,0.611
Heart surgery,0.799 [0.784–0.814],782/254048,0.894,0.499
No heart surgery,0.824 [0.812–0.834],1428/861806,0.829,0.645
SOFA < 6 (low severity),0.845 [0.833–0.858],812/636401,0.836,0.686
SOFA 6-10 (moderate severity),0.791 [0.777–0.805],859/337506,0.867,0.532
SOFA >= 11 (high severity),0.769 [0.748–0.789],539/141947,0.852,0.470
SOFA low (tertile 1),0.848 [0.829–0.868],405/385663,0.807,0.727
SOFA mid (tertile 2),0.826 [0.811–0.840],726/412321,0.864,0.602
SOFA high (tertile 3),0.770 [0.755–0.784],1079/317870,0.861,0.486
SAPS I < 14 (low severity),0.859 [0.808–0.900],67/118022,0.746,0.803
SAPS I 14-24 (moderate severity),0.817 [0.806–0.827],1468/795683,0.849,0.616
SAPS I >= 25 (high severity),0.788 [0.771–0.805],675/202149,0.870,0.486
SAPS low (tertile 1),0.862 [0.843–0.879],409/387188,0.834,0.727
SAPS mid (tertile 2),0.809 [0.795–0.825],694/362750,0.849,0.607
SAPS high (tertile 3),0.782 [0.769–0.796],1107/365916,0.861,0.495
SAPS II < 40 (low severity),0.839 [0.826–0.853],795/583589,0.826,0.692
SAPS II 40-51 (moderate severity),0.826 [0.809–0.842],491/262644,0.884,0.571
SAPS II >= 52 (high severity),0.769 [0.755–0.785],924/269621,0.857,0.478

## Generate Latex Tables

### Die titel ändern, untertitel zu den 3 spalten, formattieren

In [96]:
def escape_for_latex(s):
    return str(s).replace('_', r'\_').replace('%', r'\%') \
                 .replace('#', r'\#') \
                 .replace('<', r'$<$').replace('>', r'$>$') \
                 .replace('[', r'[').replace(']', r']') \
                 .replace('=', r'=')  # = ist meist OK außerhalb Mathemodus

def shorten_count_str(count_str):
    try:
        pos, total = count_str.strip().split('/')
        total = int(total)
        # Teile durch 1000 und runde auf eine Nachkommastelle
        if total < 1000:
            total_str = str(total)
        elif total < 100000:
            total_str = f"{round(total / 1000, 1)}K".replace(".0", "")
        else:
            total_str = f"{round(total / 1000):,}K".replace(",", "")
        return f"{pos}/{total_str}"
    except Exception as e:
        return count_str
    

def format_latex_cell(value):
    """
    Erwarteter Wert: 'auc, pos/total, sens, spec, threshold'
    Gibt zurück:
    AUC: 0.833 & Sens: 0.860 & Spec: 0.633 & [1350/659K]
    """
    try:
        parts = [p.strip() for p in value.split(',')]
        if len(parts) < 4:
            return escape_for_latex(value)

        auc, count_str, sens, spec = parts[:4]
        count_short = shorten_count_str(count_str)
        return f"{auc} & {sens} & {spec} & [{count_short}]"
    except Exception as e:
        return escape_for_latex(value)
    # 0.833 & 1350/659K & 0.86 & 0.63 



mix_biometric_translation = {
    "age_bin": {"1": "< 53.0", "2": "[53.0 - 64.5)", "3": "[64.5 - 76.0)", "4": ">= 76.0"},
    "height_bin": {"1": "< 163.0", "2": "[163.0 - 170.5)", "3": "[170.5 - 178.0)", "4": ">= 178.0"},
    "weight_bin": {"1": "< 65.6", "2": "[65.6 - 79.6)", "3": "[79.6 - 93.6)", "4": ">= 93.6"},
    "bmi_bin": {"1": "< 23.4", "2": "[23.4 - 27.7)", "3": "[27.7 - 32.1)", "4": ">= 32.1"}
}

dem_translation = {
    "gender_bin": {"0": "Male", "1": "Female"},
    "ethnicity_bin": {"0": "White", "1": "Black", "2": "Asian", "3": "Hispanic", "4": "Other"}
}


def translate_bin_names(df):
    def translate_feature(feature):
        match = re.match(r"(\w+_bin) = (\d)", str(feature))
        if match:
            bin_name, bin_value = match.groups()
            if bin_name in mix_biometric_translation:
                label = mix_biometric_translation[bin_name].get(bin_value, bin_value)
                return f"{bin_name[:-4]} {label}"
            elif bin_name in dem_translation:
                label = dem_translation[bin_name].get(bin_value, bin_value)
                return f"{bin_name[:-4]}: {label}"
        return feature

    df['Feature'] = df['Feature'].apply(translate_feature)
    return df


def bold_best_auc_in_row(row: str) -> str:
    blocks = [b.strip() for b in row.split("&")]

    # Identify AUC columns: 1, 5, 9, ... (i.e. every 4th after feature)
    auc_indices = list(range(1, len(blocks), 4))
    aucs = []

    for idx in auc_indices:
        match = re.match(r"([0-9]+\.[0-9]+)", blocks[idx])
        if match:
            aucs.append((idx, float(match.group(1))))

    if not aucs:  # no AUCs found → return unchanged
        return row

    # Find best AUC(s) (support ties)
    best_val = max(val for _, val in aucs)
    best_indices = [idx for idx, val in aucs if val == best_val]

    # Bold all best AUCs
    for idx in best_indices:
        auc_str = re.match(r"([0-9]+\.[0-9]+)", blocks[idx]).group(1)
        blocks[idx] = blocks[idx].replace(
            auc_str, f"\\textbf{{{auc_str}}}", 1
        )

    return " & ".join(blocks)

In [ ]:

df = pd.read_csv("/user/rirg2545/Projects/Hypotension-Project/src/hypotension-individual-threshold/ce_approach/evaluation/subanalysis/results_subgroup_analysis_newest.csv")

df = translate_bin_names(df)
df = df.map(format_latex_cell)


# Als LaTeX-Tabelle ausgeben (ohne Index)
latex_code = "\\begin{scriptsize}\n" + df.to_latex(index=False, escape=False) + "\n\\end{scriptsize}"

print(latex_code)

In [97]:
# 1. Load and translate bin names
df = pd.read_csv("/dss/work/rirg2545/actionable-hypotension/extended_evaluation_review/results/extended_subgroup_analysis.csv")

df = df.map(format_latex_cell)

# 2. Convert DataFrame to LaTeX string
latex_code = df.to_latex(index=False, escape=False)

# 3. Postprocess each LaTeX row to bold the best AUC
processed_lines = []
for line in latex_code.splitlines():
    if "&" in line and not line.strip().startswith("\\"):  # skip headers/commands
        line = bold_best_auc_in_row(line)
    processed_lines.append(line)

# 4. Wrap in LaTeX environment
final_latex = "\\begin{scriptsize}\n" + "\n".join(processed_lines) + "\n\\end{scriptsize}"

print(final_latex)

\begin{scriptsize}
\begin{tabular}{ll}
\toprule
Subgroup & mix \\
\midrule
All patients & \textbf{0.822} [0.813–0.830] & sens=0.852 & spec=0.612 & [2212/1116K] \\
Excluded patients & \textbf{0.758} [0.730–0.786] & sens=0.665 & spec=0.722 & [343/202K] \\
Non-excluded patients & \textbf{0.834} [0.825–0.842] & sens=0.886 & spec=0.588 & [1867/914K] \\
Age $<$ 70 & \textbf{0.824} [0.812–0.835] & sens=0.839 & spec=0.646 & [1133/646K] \\
Age 70-80 & \textbf{0.809} [0.793–0.824] & sens=0.864 & spec=0.560 & [602/233K] \\
Age 80-85 & \textbf{0.823} [0.795–0.851] & sens=0.857 & spec=0.570 & [231/115K] \\
Age $>$ 85 & \textbf{0.827} [0.797–0.856] & sens=0.878 & spec=0.572 & [196/101K] \\
Surgical ICU & \textbf{0.810} [0.798–0.823] & sens=0.833 & spec=0.613 & [1268/555K] \\
Non-surgical ICU & \textbf{0.836} [0.824–0.848] & sens=0.878 & spec=0.611 & [942/561K] \\
Heart surgery & \textbf{0.799} [0.782–0.813] & sens=0.894 & spec=0.499 & [782/254K] \\
No heart surgery & \textbf{0.824} [0.813–0.835] & sens=0.829 & spec=0.645 & [1428/862K] \\
SOFA $<$ 6 (low severity) & \textbf{0.845} [0.831–0.858] & sens=0.836 & spec=0.686 & [812/636K] \\
SOFA 6-10 (moderate severity) & \textbf{0.791} [0.776–0.806] & sens=0.867 & spec=0.532 & [859/338K] \\
SOFA $>$= 11 (high severity) & \textbf{0.769} [0.750–0.789] & sens=0.852 & spec=0.470 & [539/142K] \\
SOFA low (tertile 1) & \textbf{0.848} [0.828–0.868] & sens=0.807 & spec=0.727 & [405/386K] \\
SOFA mid (tertile 2) & \textbf{0.826} [0.811–0.840] & sens=0.864 & spec=0.602 & [726/412K] \\
SOFA high (tertile 3) & \textbf{0.770} [0.756–0.784] & sens=0.861 & spec=0.486 & [1079/318K] \\
SAPS II $<$ 40 (low severity) & \textbf{0.821} [0.813–0.830] & sens=0.852 & spec=0.612 & [2200/1116K] \\
SAPS II 40-51 (moderate severity) & \textbf{0.490} [0.270–0.719] & sens=0.900 & spec=0.057 & [10/203] \\
SAPS low (tertile 1) & \textbf{0.840} [0.820–0.862] & sens=0.812 & spec=0.723 & [377/383K] \\
SAPS mid (tertile 2) & \textbf{0.818} [0.804–0.830] & sens=0.866 & spec=0.590 & [799/393K] \\
SAPS high (tertile 3) & \textbf{0.786} [0.771–0.799] & sens=0.856 & spec=0.512 & [1034/341K] \\
\bottomrule
\end{tabular}
\end{scriptsize}